blueprint:
  name: Fenêtre ouverte, chauffage éteint avec retard
  description: Éteint le chauffage ou l'appareil de climatisation après un certain temps une fois la fenêtre ouverte. Lorsque la fenêtre est refermée, le chauffage se rallume automatiquement.
  domain: automation
  input:
    window_entity:
      name: Capteur de fenêtre
      description: Capteur qui contrôle le thermostat.
      selector:
        entity:
          domain: binary_sensor
    minimum_open_time:
      name: Délai temporel
      description: Temps avant que l'automatisation soit déclenchée
      default: 12
      selector:
        number:
          min: 0.0
          max: 120.0
          unit_of_measurement: secondes
          mode: slider
          step: 1.0
    minimum_close_time:
      name: Temps de fermeture minimum
      description: Temps en secondes à attendre avant que le thermostat ne soit rallumé
      default: 12
      selector:
        number:
          min: 0.0
          max: 600.0
          unit_of_measurement: secondes
          mode: slider
          step: 1.0
    climate_target:
      name: Thermostat
      description: Chauffage ou climatisation qui doit réagir au capteur de fenêtre.
      selector:
        entity:
          domain: climate

trigger:
  - platform: state
    entity_id: !input window_entity
    to: 'on'
    for: !input 'minimum_open_time'
condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: !input 'climate_target'
      attribute: hvac_action
      state: 'off'
action:
  - service: climate.turn_off
    entity_id: !input climate_target
  - wait_for_trigger:
    - platform: state
      entity_id: !input window_entity
      to: 'off'
    continue_on_timeout: false
  - delay: !input 'minimum_close_time'
  - service: climate.turn_on
    entity_id: !input climate_target
